# Generated by Django 4.0.2 on 2022-02-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.media')),
            ],
            bases=('troveapi.media',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.media')),
                ('multiplayer_capable', models.BooleanField()),
            ],
            bases=('troveapi.media',),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.media')),
                ('streaming_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.streamingservice')),
            ],
            bases=('troveapi.media',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedShow',
            fields=[
                ('taggedmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.taggedmedia')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.show')),
            ],
            bases=('troveapi.taggedmedia',),
        ),
        migrations.CreateModel(
            name='TaggedGame',
            fields=[
                ('taggedmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.taggedmedia')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.game')),
            ],
            bases=('troveapi.taggedmedia',),
        ),
        migrations.CreateModel(
            name='TaggedBook',
            fields=[
                ('taggedmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.taggedmedia')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.book')),
            ],
            bases=('troveapi.taggedmedia',),
        ),
        migrations.CreateModel(
            name='ShowRecommendation',
            fields=[
                ('recommendation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.recommendation')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.show')),
            ],
            bases=('troveapi.recommendation',),
        ),
        migrations.CreateModel(
            name='GameRecommendation',
            fields=[
                ('recommendation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.recommendation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.game')),
            ],
            bases=('troveapi.recommendation',),
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.platform')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.game')),
            ],
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('recommendation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troveapi.recommendation')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.book')),
            ],
            bases=('troveapi.recommendation',),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troveapi.author'),
        ),
    ]
