# Generated by Django 4.0.2 on 2022-02-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troveapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='bookTags', through='troveapi.TaggedBook', to='troveapi.Tag'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='platforms', through='troveapi.GamePlatform', to='troveapi.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='gameTags', through='troveapi.TaggedGame', to='troveapi.Tag'),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(related_name='showTags', through='troveapi.TaggedShow', to='troveapi.Tag'),
        ),
    ]
