# Generated by Django 4.0.2 on 2022-02-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troveapi', '0003_book_last_modified_game_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='troveapi.author'),
        ),
    ]
